### ISSUE TITLE
Debian package appserver-runtime misses dependency libfreetype6

### ISSUE THREAD

**Issue by waja** [appserver-io-dist/debian#33]
$ /opt/appserver/bin/php -v
./bin/php: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
$ apt-cache show appserver-dist | grep libfreetype6
$

**Comment by wagnert** [comment]
Hi, thanks for adding the issue! To find the reason, why libfreetype6 is not installed it would be helpful to know, if you installed Debian with the standard or the expert mode?

**Comment by waja** [comment]
@wagnert it's a docker instance and it has just installed a minimal set of packages. It's basically a debootstrap based installation. It doesn't matter in the end, why libfreetype6 isn't installed. If you package depend on this package, it should be listed there to make sure it get's installed.

**Comment by waja** [comment]
@wagnert seems you got that issue too: https://github.com/appserver-io-dist/docker/blob/master/Dockerfile#L7
