### ISSUE TITLE
status command not found

### ISSUE THREAD

**Issue by tobemedia** [appserver-io-dist/debian#35]
on a fresh Debian 7.8.0 install a

/etc/init.d/appserver-watcher status causes this output / error:
Status of Appserver Watcher aka Deployment Scanner: /etc/init.d/appserver-watcher: line 58: status: command not found

and

/etc/init.d/appserver status
Status of appserver: /etc/init.d/appserver: line 66: status: command not found

**Comment by wick-ed** [comment]
Solved as of [this commit](https://github.com/appserver-io-dist/debian/commit/632eb1a982ee5a4bfc12096a5312c25e71d4dfe7). Coming builds will include a working SysVinit `status` command.
